import { HttpClientModule } from '@angular/common/http';
import { MatIconModule } from '@angular/material/icon';
import { object, radios } from '@storybook/addon-knobs';
import { TagComponent } from '../tags/regular/tag.component';
import { CodeReviewItemComponent } from './code-review-item/code-review-item.component';
import { CodeReviewUsersComponent } from './code-review-users/code-review-users.component';

export default {
  title: 'Code Review',
};

export const noUser = () => ({
  moduleMetadata: {
    imports: [],
    declarations: [CodeReviewUsersComponent],
  },
  component: CodeReviewUsersComponent,
  template: `<gitcode-code-review-users [users]='users'
                                        [userType]='userType'
                                        [isBestReviewer]='isBestReviewer'></gitcode-code-review-users>`,
  props: {
    userType: radios('User Type', { author: 'author', reviewers: 'reviewers' }, 'author'),
    isBestReviewer: radios('Is Best Reviewer', { true: 'true', false: 'false' }, 'false'),
    users: [],
  },
});

export const user = () => ({
  moduleMetadata: {
    imports: [],
    declarations: [CodeReviewUsersComponent],
  },
  component: CodeReviewUsersComponent,
  template: `<gitcode-code-review-users [users]='users'
                                        [userType]='userType'
                                        [isBestReviewer]='isBestReviewer'></gitcode-code-review-users>`,
  props: {
    userType: radios('User Type', { author: 'author', reviewers: 'reviewers' }, 'author'),
    isBestReviewer: radios('Is Best Reviewer', { true: 'true', false: 'false' }, 'false'),
    users: [{ name: 'spock', photoUrl: 'https://avatars2.githubusercontent.com/u/18748215?v=4' }],
  },
});

export const users = () => ({
  moduleMetadata: {
    imports: [],
    declarations: [CodeReviewUsersComponent],
  },
  component: CodeReviewUsersComponent,
  template: `<gitcode-code-review-users [users]='users'
                                        [userType]='userType'
                                        [isBestReviewer]='isBestReviewer'></gitcode-code-review-users>`,
  props: {
    userType: radios('User Type', { author: 'author', reviewers: 'reviewers' }, 'author'),
    isBestReviewer: radios('Is Best Reviewer', { true: 'true', false: 'false' }, 'false'),
    users: [
      { name: 'Joris', photoUrl: 'https://i.pravatar.cc/40?img=11' },
      { name: 'Rax', photoUrl: 'https://i.pravatar.cc/40?img=12' },
      { name: 'Ximo', photoUrl: 'https://i.pravatar.cc/40?img=13' },
      { name: 'Anet', photoUrl: 'https://i.pravatar.cc/40?img=14' },
      { name: 'Tord', photoUrl: 'https://i.pravatar.cc/40?img=15' },
      { name: 'Aisha', photoUrl: 'https://i.pravatar.cc/40?img=16' },
      { name: 'Uri', photoUrl: 'https://i.pravatar.cc/40?img=17' },
      { name: 'Enoc', photoUrl: 'https://i.pravatar.cc/40?img=18' },
      { name: 'Elife', photoUrl: 'https://i.pravatar.cc/40?img=19' },
      { name: 'Jake', photoUrl: 'https://i.pravatar.cc/40?img=20' },
    ],
  },
});

export const item = () => ({
  moduleMetadata: {
    imports: [
      HttpClientModule,
      MatIconModule,
    ],
    declarations: [
      CodeReviewItemComponent,
      CodeReviewUsersComponent,
      TagComponent,
    ],
  },
  component: CodeReviewItemComponent,
  template: `<gitcode-code-review-item [codeReviewItem]='codeReviewItem'
                                       (itemClicked)='onClicked($event)'></gitcode-code-review-item>`,
  props: {
    codeReviewItem: object('Code Review Item', {
      'githubPR': {
        'draft': false,
        'merged': false,
        'user': {
          'followers_url': 'https://api.github.com/users/spock-mark1/followers',
          'node_id': 'MDQ6VXNlcjE4NzQ4MjE1',
          'events_url': 'https://api.github.com/users/spock-mark1/events{/privacy}',
          'starred_url': 'https://api.github.com/users/spock-mark1/starred{/owner}{/repo}',
          'organizations_url': 'https://api.github.com/users/spock-mark1/orgs',
          'id': 18748215,
          'site_admin': false,
          'gists_url': 'https://api.github.com/users/spock-mark1/gists{/gist_id}',
          'avatar_url': 'https://avatars2.githubusercontent.com/u/18748215?v=4',
          'received_events_url': 'https://api.github.com/users/spock-mark1/received_events',
          'html_url': 'https://github.com/spock-mark1',
          'url': 'https://api.github.com/users/spock-mark1',
          'following_url': 'https://api.github.com/users/spock-mark1/following{/other_user}',
          'login': 'spock-mark1',
          'subscriptions_url': 'https://api.github.com/users/spock-mark1/subscriptions',
          'type': 'User',
          'gravatar_id': '',
          'repos_url': 'https://api.github.com/users/spock-mark1/repos',
        },
        'diff_url': 'https://github.com/spock-mark1/serverless/pull/19.diff',
        'deletions': 13,
        'changed_files': 5,
        'state': 'open',
        'additions': 16,
        'title': 'test',
        'assignee': null,
        'milestone': null,
        'merge_commit_sha': null,
        'mergeable': null,
        'requested_reviewers': [],
        'review_comments': 0,
        'merged_at': null,
        'comments': 0,
        'number': 19,
        'issue_url': 'https://api.github.com/repos/spock-mark1/serverless/issues/19',
        'review_comment_url': 'https://api.github.com/repos/spock-mark1/serverless/pulls/comments{/number}',
        'active_lock_reason': null,
        'locked': false,
        'assignees': [],
        '_links': {
          'html': {
            'href': 'https://github.com/spock-mark1/serverless/pull/19',
          },
          'issue': {
            'href': 'https://api.github.com/repos/spock-mark1/serverless/issues/19',
          },
          'self': {
            'href': 'https://api.github.com/repos/spock-mark1/serverless/pulls/19',
          },
          'commits': {
            'href': 'https://api.github.com/repos/spock-mark1/serverless/pulls/19/commits',
          },
          'review_comment': {
            'href': 'https://api.github.com/repos/spock-mark1/serverless/pulls/comments{/number}',
          },
          'review_comments': {
            'href': 'https://api.github.com/repos/spock-mark1/serverless/pulls/19/comments',
          },
          'statuses': {
            'href': 'https://api.github.com/repos/spock-mark1/serverless/statuses/e2b9038ff7614e7979b8a52b441b8b7197169bf3',
          },
          'comments': {
            'href': 'https://api.github.com/repos/spock-mark1/serverless/issues/19/comments',
          },
        },
        'patch_url': 'https://github.com/spock-mark1/serverless/pull/19.patch',
        'rebaseable': null,
        'statuses_url': 'https://api.github.com/repos/spock-mark1/serverless/statuses/e2b9038ff7614e7979b8a52b441b8b7197169bf3',
        'review_comments_url': 'https://api.github.com/repos/spock-mark1/serverless/pulls/19/comments',
        'html_url': 'https://github.com/spock-mark1/serverless/pull/19',
        'comments_url': 'https://api.github.com/repos/spock-mark1/serverless/issues/19/comments',
        'commits': 5,
        'labels': [],
        'base': {
          'label': 'spock-mark1:cypressdocs',
          'ref': 'cypressdocs',
          'user': {
            'site_admin': false,
            'node_id': 'MDQ6VXNlcjE4NzQ4MjE1',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/spock-mark1',
            'id': 18748215,
            'received_events_url': 'https://api.github.com/users/spock-mark1/received_events',
            'type': 'User',
            'events_url': 'https://api.github.com/users/spock-mark1/events{/privacy}',
            'subscriptions_url': 'https://api.github.com/users/spock-mark1/subscriptions',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/18748215?v=4',
            'starred_url': 'https://api.github.com/users/spock-mark1/starred{/owner}{/repo}',
            'gists_url': 'https://api.github.com/users/spock-mark1/gists{/gist_id}',
            'following_url': 'https://api.github.com/users/spock-mark1/following{/other_user}',
            'login': 'spock-mark1',
            'organizations_url': 'https://api.github.com/users/spock-mark1/orgs',
            'html_url': 'https://github.com/spock-mark1',
            'repos_url': 'https://api.github.com/users/spock-mark1/repos',
            'followers_url': 'https://api.github.com/users/spock-mark1/followers',
          },
          'sha': 'c43004a15f26ada42fb78b1411834c4d53ea5eb2',
          'repo': {
            'events_url': 'https://api.github.com/repos/spock-mark1/serverless/events',
            'issue_comment_url': 'https://api.github.com/repos/spock-mark1/serverless/issues/comments{/number}',
            'license': {
              'node_id': 'MDc6TGljZW5zZTEz',
              'name': 'MIT License',
              'url': 'https://api.github.com/licenses/mit',
              'key': 'mit',
              'spdx_id': 'MIT',
            },
            'notifications_url': 'https://api.github.com/repos/spock-mark1/serverless/notifications{?since,all,participating}',
            'homepage': 'https://serverless.com',
            'has_projects': true,
            'has_downloads': true,
            'ssh_url': 'git@github.com:spock-mark1/serverless.git',
            'size': 86763,
            'compare_url': 'https://api.github.com/repos/spock-mark1/serverless/compare/{base}...{head}',
            'downloads_url': 'https://api.github.com/repos/spock-mark1/serverless/downloads',
            'has_wiki': false,
            'pulls_url': 'https://api.github.com/repos/spock-mark1/serverless/pulls{/number}',
            'forks_count': 0,
            'name': 'serverless',
            'subscribers_url': 'https://api.github.com/repos/spock-mark1/serverless/subscribers',
            'git_tags_url': 'https://api.github.com/repos/spock-mark1/serverless/git/tags{/sha}',
            'branches_url': 'https://api.github.com/repos/spock-mark1/serverless/branches{/branch}',
            'watchers': 0,
            'tags_url': 'https://api.github.com/repos/spock-mark1/serverless/tags',
            'watchers_count': 0,
            'fork': true,
            'id': 272947259,
            'issue_events_url': 'https://api.github.com/repos/spock-mark1/serverless/issues/events{/number}',
            'full_name': 'spock-mark1/serverless',
            'git_url': 'git://github.com/spock-mark1/serverless.git',
            'stargazers_url': 'https://api.github.com/repos/spock-mark1/serverless/stargazers',
            'has_issues': false,
            'contributors_url': 'https://api.github.com/repos/spock-mark1/serverless/contributors',
            'owner': {
              'id': 18748215,
              'received_events_url': 'https://api.github.com/users/spock-mark1/received_events',
              'gists_url': 'https://api.github.com/users/spock-mark1/gists{/gist_id}',
              'events_url': 'https://api.github.com/users/spock-mark1/events{/privacy}',
              'subscriptions_url': 'https://api.github.com/users/spock-mark1/subscriptions',
              'following_url': 'https://api.github.com/users/spock-mark1/following{/other_user}',
              'type': 'User',
              'organizations_url': 'https://api.github.com/users/spock-mark1/orgs',
              'repos_url': 'https://api.github.com/users/spock-mark1/repos',
              'starred_url': 'https://api.github.com/users/spock-mark1/starred{/owner}{/repo}',
              'login': 'spock-mark1',
              'html_url': 'https://github.com/spock-mark1',
              'url': 'https://api.github.com/users/spock-mark1',
              'gravatar_id': '',
              'site_admin': false,
              'followers_url': 'https://api.github.com/users/spock-mark1/followers',
              'node_id': 'MDQ6VXNlcjE4NzQ4MjE1',
              'avatar_url': 'https://avatars2.githubusercontent.com/u/18748215?v=4',
            },
            'subscription_url': 'https://api.github.com/repos/spock-mark1/serverless/subscription',
            'statuses_url': 'https://api.github.com/repos/spock-mark1/serverless/statuses/{sha}',
            'open_issues': 1,
            'html_url': 'https://github.com/spock-mark1/serverless',
            'disabled': false,
            'trees_url': 'https://api.github.com/repos/spock-mark1/serverless/git/trees{/sha}',
            'svn_url': 'https://github.com/spock-mark1/serverless',
            'forks': 0,
            'issues_url': 'https://api.github.com/repos/spock-mark1/serverless/issues{/number}',
            'has_pages': false,
            'teams_url': 'https://api.github.com/repos/spock-mark1/serverless/teams',
            'git_refs_url': 'https://api.github.com/repos/spock-mark1/serverless/git/refs{/sha}',
            'releases_url': 'https://api.github.com/repos/spock-mark1/serverless/releases{/id}',
            'milestones_url': 'https://api.github.com/repos/spock-mark1/serverless/milestones{/number}',
            'assignees_url': 'https://api.github.com/repos/spock-mark1/serverless/assignees{/user}',
            'hooks_url': 'https://api.github.com/repos/spock-mark1/serverless/hooks',
            'archive_url': 'https://api.github.com/repos/spock-mark1/serverless/{archive_format}{/ref}',
            'keys_url': 'https://api.github.com/repos/spock-mark1/serverless/keys{/key_id}',
            'pushed_at': '2020-06-17T19:16:58Z',
            'git_commits_url': 'https://api.github.com/repos/spock-mark1/serverless/git/commits{/sha}',
            'default_branch': 'master',
            'node_id': 'MDEwOlJlcG9zaXRvcnkyNzI5NDcyNTk=',
            'mirror_url': null,
            'created_at': '2020-06-17T10:41:00Z',
            'forks_url': 'https://api.github.com/repos/spock-mark1/serverless/forks',
            'languages_url': 'https://api.github.com/repos/spock-mark1/serverless/languages',
            'description': '⚡ Serverless Framework – Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more! – ',
            'clone_url': 'https://github.com/spock-mark1/serverless.git',
            'commits_url': 'https://api.github.com/repos/spock-mark1/serverless/commits{/sha}',
            'deployments_url': 'https://api.github.com/repos/spock-mark1/serverless/deployments',
            'stargazers_count': 0,
            'contents_url': 'https://api.github.com/repos/spock-mark1/serverless/contents/{+path}',
            'archived': false,
            'updated_at': '2020-06-17T19:04:14Z',
            'language': null,
            'open_issues_count': 1,
            'labels_url': 'https://api.github.com/repos/spock-mark1/serverless/labels{/name}',
            'collaborators_url': 'https://api.github.com/repos/spock-mark1/serverless/collaborators{/collaborator}',
            'comments_url': 'https://api.github.com/repos/spock-mark1/serverless/comments{/number}',
            'merges_url': 'https://api.github.com/repos/spock-mark1/serverless/merges',
            'url': 'https://api.github.com/repos/spock-mark1/serverless',
            'private': false,
            'blobs_url': 'https://api.github.com/repos/spock-mark1/serverless/git/blobs{/sha}',
          },
        },
        'requested_teams': [],
        'created_at': '2020-06-17T19:21:59Z',
        'author_association': 'OWNER',
        'url': 'https://api.github.com/repos/spock-mark1/serverless/pulls/19',
        'id': 436048069,
        'updated_at': '2020-06-17T19:21:59Z',
        'merged_by': null,
        'node_id': 'MDExOlB1bGxSZXF1ZXN0NDM2MDQ4MDY5',
        'maintainer_can_modify': false,
        'closed_at': null,
        'mergeable_state': 'unknown',
        'commits_url': 'https://api.github.com/repos/spock-mark1/serverless/pulls/19/commits',
        'body': 'test\n\ntest',
        'head': {
          'ref': 'components-v2',
          'label': 'spock-mark1:components-v2',
          'user': {
            'html_url': 'https://github.com/spock-mark1',
            'id': 18748215,
            'following_url': 'https://api.github.com/users/spock-mark1/following{/other_user}',
            'login': 'spock-mark1',
            'events_url': 'https://api.github.com/users/spock-mark1/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/spock-mark1/received_events',
            'organizations_url': 'https://api.github.com/users/spock-mark1/orgs',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/18748215?v=4',
            'followers_url': 'https://api.github.com/users/spock-mark1/followers',
            'gravatar_id': '',
            'subscriptions_url': 'https://api.github.com/users/spock-mark1/subscriptions',
            'site_admin': false,
            'node_id': 'MDQ6VXNlcjE4NzQ4MjE1',
            'starred_url': 'https://api.github.com/users/spock-mark1/starred{/owner}{/repo}',
            'url': 'https://api.github.com/users/spock-mark1',
            'type': 'User',
            'gists_url': 'https://api.github.com/users/spock-mark1/gists{/gist_id}',
            'repos_url': 'https://api.github.com/users/spock-mark1/repos',
          },
          'repo': {
            'events_url': 'https://api.github.com/repos/spock-mark1/serverless/events',
            'blobs_url': 'https://api.github.com/repos/spock-mark1/serverless/git/blobs{/sha}',
            'forks': 0,
            'has_pages': false,
            'subscription_url': 'https://api.github.com/repos/spock-mark1/serverless/subscription',
            'pulls_url': 'https://api.github.com/repos/spock-mark1/serverless/pulls{/number}',
            'git_tags_url': 'https://api.github.com/repos/spock-mark1/serverless/git/tags{/sha}',
            'forks_url': 'https://api.github.com/repos/spock-mark1/serverless/forks',
            'subscribers_url': 'https://api.github.com/repos/spock-mark1/serverless/subscribers',
            'releases_url': 'https://api.github.com/repos/spock-mark1/serverless/releases{/id}',
            'has_issues': false,
            'node_id': 'MDEwOlJlcG9zaXRvcnkyNzI5NDcyNTk=',
            'id': 272947259,
            'pushed_at': '2020-06-17T19:16:58Z',
            'created_at': '2020-06-17T10:41:00Z',
            'updated_at': '2020-06-17T19:04:14Z',
            'issues_url': 'https://api.github.com/repos/spock-mark1/serverless/issues{/number}',
            'has_downloads': true,
            'git_commits_url': 'https://api.github.com/repos/spock-mark1/serverless/git/commits{/sha}',
            'labels_url': 'https://api.github.com/repos/spock-mark1/serverless/labels{/name}',
            'forks_count': 0,
            'size': 86763,
            'notifications_url': 'https://api.github.com/repos/spock-mark1/serverless/notifications{?since,all,participating}',
            'issue_comment_url': 'https://api.github.com/repos/spock-mark1/serverless/issues/comments{/number}',
            'commits_url': 'https://api.github.com/repos/spock-mark1/serverless/commits{/sha}',
            'tags_url': 'https://api.github.com/repos/spock-mark1/serverless/tags',
            'full_name': 'spock-mark1/serverless',
            'stargazers_count': 0,
            'ssh_url': 'git@github.com:spock-mark1/serverless.git',
            'archived': false,
            'hooks_url': 'https://api.github.com/repos/spock-mark1/serverless/hooks',
            'disabled': false,
            'html_url': 'https://github.com/spock-mark1/serverless',
            'private': false,
            'open_issues': 1,
            'language': null,
            'contributors_url': 'https://api.github.com/repos/spock-mark1/serverless/contributors',
            'description': '⚡ Serverless Framework – Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more! – ',
            'has_wiki': false,
            'watchers_count': 0,
            'statuses_url': 'https://api.github.com/repos/spock-mark1/serverless/statuses/{sha}',
            'compare_url': 'https://api.github.com/repos/spock-mark1/serverless/compare/{base}...{head}',
            'git_refs_url': 'https://api.github.com/repos/spock-mark1/serverless/git/refs{/sha}',
            'svn_url': 'https://github.com/spock-mark1/serverless',
            'assignees_url': 'https://api.github.com/repos/spock-mark1/serverless/assignees{/user}',
            'branches_url': 'https://api.github.com/repos/spock-mark1/serverless/branches{/branch}',
            'fork': true,
            'watchers': 0,
            'git_url': 'git://github.com/spock-mark1/serverless.git',
            'mirror_url': null,
            'issue_events_url': 'https://api.github.com/repos/spock-mark1/serverless/issues/events{/number}',
            'open_issues_count': 1,
            'contents_url': 'https://api.github.com/repos/spock-mark1/serverless/contents/{+path}',
            'keys_url': 'https://api.github.com/repos/spock-mark1/serverless/keys{/key_id}',
            'homepage': 'https://serverless.com',
            'archive_url': 'https://api.github.com/repos/spock-mark1/serverless/{archive_format}{/ref}',
            'comments_url': 'https://api.github.com/repos/spock-mark1/serverless/comments{/number}',
            'clone_url': 'https://github.com/spock-mark1/serverless.git',
            'collaborators_url': 'https://api.github.com/repos/spock-mark1/serverless/collaborators{/collaborator}',
            'teams_url': 'https://api.github.com/repos/spock-mark1/serverless/teams',
            'owner': {
              'received_events_url': 'https://api.github.com/users/spock-mark1/received_events',
              'node_id': 'MDQ6VXNlcjE4NzQ4MjE1',
              'following_url': 'https://api.github.com/users/spock-mark1/following{/other_user}',
              'subscriptions_url': 'https://api.github.com/users/spock-mark1/subscriptions',
              'avatar_url': 'https://avatars2.githubusercontent.com/u/18748215?v=4',
              'url': 'https://api.github.com/users/spock-mark1',
              'type': 'User',
              'starred_url': 'https://api.github.com/users/spock-mark1/starred{/owner}{/repo}',
              'events_url': 'https://api.github.com/users/spock-mark1/events{/privacy}',
              'site_admin': false,
              'id': 18748215,
              'repos_url': 'https://api.github.com/users/spock-mark1/repos',
              'login': 'spock-mark1',
              'gists_url': 'https://api.github.com/users/spock-mark1/gists{/gist_id}',
              'organizations_url': 'https://api.github.com/users/spock-mark1/orgs',
              'gravatar_id': '',
              'html_url': 'https://github.com/spock-mark1',
              'followers_url': 'https://api.github.com/users/spock-mark1/followers',
            },
            'default_branch': 'master',
            'url': 'https://api.github.com/repos/spock-mark1/serverless',
            'trees_url': 'https://api.github.com/repos/spock-mark1/serverless/git/trees{/sha}',
            'deployments_url': 'https://api.github.com/repos/spock-mark1/serverless/deployments',
            'milestones_url': 'https://api.github.com/repos/spock-mark1/serverless/milestones{/number}',
            'downloads_url': 'https://api.github.com/repos/spock-mark1/serverless/downloads',
            'has_projects': true,
            'stargazers_url': 'https://api.github.com/repos/spock-mark1/serverless/stargazers',
            'license': {
              'spdx_id': 'MIT',
              'url': 'https://api.github.com/licenses/mit',
              'name': 'MIT License',
              'key': 'mit',
              'node_id': 'MDc6TGljZW5zZTEz',
            },
            'merges_url': 'https://api.github.com/repos/spock-mark1/serverless/merges',
            'name': 'serverless',
            'languages_url': 'https://api.github.com/repos/spock-mark1/serverless/languages',
          },
          'sha': 'e2b9038ff7614e7979b8a52b441b8b7197169bf3',
        },
      },
      'state': 'reviewing',
      'description': 'test',
      'updatedAt': '2020-06-18T09:14:15.419Z',
      'author': {
        'displayName': 'spock',
        'providerUserData': {
          'github': {
            'subscriptions_url': 'https://api.github.com/users/spock-mark1/subscriptions',
            'collaborators': 7,
            'received_events_url': 'https://api.github.com/users/spock-mark1/received_events',
            'blog': '',
            'bio': null,
            'public_repos': 3,
            'following': 5,
            'site_admin': false,
            'gists_url': 'https://api.github.com/users/spock-mark1/gists{/gist_id}',
            'company': null,
            'followers': 6,
            'url': 'https://api.github.com/users/spock-mark1',
            'hireable': true,
            'two_factor_authentication': false,
            'repos_url': 'https://api.github.com/users/spock-mark1/repos',
            'followers_url': 'https://api.github.com/users/spock-mark1/followers',
            'events_url': 'https://api.github.com/users/spock-mark1/events{/privacy}',
            'name': 'spock',
            'twitter_username': null,
            'public_gists': 0,
            'total_private_repos': 11,
            'gravatar_id': '',
            'starred_url': 'https://api.github.com/users/spock-mark1/starred{/owner}{/repo}',
            'private_gists': 0,
            'login': 'spock-mark1',
            'organizations_url': 'https://api.github.com/users/spock-mark1/orgs',
            'disk_usage': 147657,
            'html_url': 'https://github.com/spock-mark1',
            'id': 18748215,
            'email': null,
            'created_at': '2016-04-30T06:03:57Z',
            'owned_private_repos': 11,
            'following_url': 'https://api.github.com/users/spock-mark1/following{/other_user}',
            'plan': {
              'space': 976562499,
              'collaborators': 0,
              'name': 'pro',
              'private_repos': 9999,
            },
            'updated_at': '2020-06-17T11:14:00Z',
            'node_id': 'MDQ6VXNlcjE4NzQ4MjE1',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/18748215?v=4',
            'location': null,
            'type': 'User',
          },
        },
        'photoURL': 'https://avatars2.githubusercontent.com/u/18748215?v=4',
        'uid': '8xR47FqO0Wd0tvR8PFzQVaAHQXg1',
        'email': 'david.kang200@gmail.com',
        'lastLogin': '2020-06-17T12:31:12.446Z',
        'accessToken': '40a7ba1874dee83905a888d1969ccba20afba4a4',
      },
      'purpose': 'test',
      'title': 'test',
      'createdAt': '2020-06-17T19:22:00.211Z',
      'reviewers': [
        {
          'createdAt': '2020-06-18T09:14:15.581Z',
          'name': 'iamappple',
          'nodeId': 'MDQ6VXNlcjU1OTgzMTIy',
          'profileUrl': 'https://github.com/iamappple',
          'photoUrl': 'https://avatars0.githubusercontent.com/u/55983122?v=4',
        },
      ],
      'topics': [],
      'proficiency': 'intermediate',
    }),
    onClicked: (codeReviewItem) => {
      console.log(codeReviewItem);
    },
  },
});
